name: sdss-classifier
channels:
  - conda-forge
  - defaults

dependencies:
  - ipython=8.8.0  # a powerful Python shell
  - ipywidgets=8.0.2  # optionally used only in chapter 12 for tqdm in Jupyter
  - jupyterlab=3.5.2  # to edit and run Jupyter notebooks
  - matplotlib=3.6  # beautiful plots. See tutorial tools_matplotlib.ipynb
  - numpy=1.24  # Powerful n-dimensional arrays and numerical computing tools
  - pandas=1.5.2  # data analysis and manipulation tool
  - pillow=9.4  # image manipulation library, (used by matplotlib.image.imread)
  - pip  # Python's package-management system
  - python=3.10.8  # your beloved programming language! :)
  - requests=2.28  # used only in chapter 19 for REST API queries
  - scikit-learn=1.2.0  # machine learning library
  - scipy=1.10  # scientific/technical computing library
